import './globals.css'
import { Inter } from 'next/font/google'
import { CssBaseline, ThemeProvider } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NPC Village',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
